export { ReactComponent as Logo } from "./logo.svg";
export { ReactComponent as Architecture } from "./architecture.svg";
export { ReactComponent as Construction } from "./construction.svg";
export { ReactComponent as Equipment } from "./equipment.svg";
export { ReactComponent as Pipelines } from "./pipelines.svg";
export { ReactComponent as Subsea } from "./subsea.svg";
export { ReactComponent as Facebook } from "./facebook.svg";
export { ReactComponent as Instagram } from "./instagram.svg";
export { ReactComponent as Tiktok } from "./tiktok.svg";